import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/navbar";
import { ViewModeProvider } from "@/context/ViewModeContext";

const PPEditorialNew = localFont({
  src: [
    {
      path: "../fonts/PPEditorialNew-Ultralight.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-PPeditorialNew",
  display: "swap",
});

const SuisseIntl = localFont({
  src: [
    {
      path: "../fonts/SuisseIntl-Regular-WebXL.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-SuisseIntl",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPEditorialNew.variable} ${SuisseIntl.variable} antialiased`}
      >
        <ViewModeProvider>
          <Navbar />
          {children}
        </ViewModeProvider>
      </body>
    </html>
  );
}
